name: Question
description: Wanna ask something?
title: "[QUESTION]: "
labels: ["question"]
assignees:
  - skuqre
body:
  - type: textarea
    id: description
    attributes:
      label: What's your question?
      placeholder: Be sure to put a brief version of your question on the title.
    validations:
      required: true
