# This is a basic workflow to help you get started with Actions
# from Kade Engine github
# Also takes some things from Psych Engine github

name: Build

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windows:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.4
      # Runs a set of commands using the runners shell
      - name: Install Libraries
        run: |
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel --always
          haxelib run lime setup -y
          haxelib install flixel-tools
          haxelib git flixel-addons
          haxelib install flixel-ui
          haxelib git hscript https://github.com/skuqre/hscript
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib install flixel-addons
          haxelib install yaml
          haxelib install actuate
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list
      - name: Build
        run: haxelib run lime build mac
      - uses: actions/upload-artifact@v2
        with:
          name: Mac Build
          path: export/release/macos/bin
